using ArchUnitNET.Core;
using ArchUnitNET.Loader;
using ArchUnitNET.xUnit;
using Xunit;
using static ArchUnitNET.Fluent.ArchRuleDefinition;

namespace TestArchUnit.Architecture.Tests;

/// <summary>
/// Architecture tests for validating license compliance and architecture constraints.
/// </summary>
public class LicenseComplianceTests
{
    private static readonly Architecture Architecture =
        new ArchLoader().LoadAssemblies(typeof(Architecture).Assembly).Build();

    /// <summary>
    /// Validates that no GPL 3 licensed libraries are used in the solution.
    /// 
    /// GPL 3 is a copyleft license that can impose viral licensing requirements.
    /// This test ensures the project uses only compatible open source licenses.
    /// </summary>
    [Fact]
    public void NoGpl3LicensedDependencies()
    {
        // List of known GPL 3 licensed NuGet packages that should NOT be used
        var gpl3LicensedPackages = new[]
        {
            "AGPL",
            "GPL-3",
            "GPLv3"
        };

        // Get all dependencies from the API project
        var apiAssembly = Architecture.GetAssembliesByName("TestArchUnit.API").FirstOrDefault();
        
        var rule = Types()
            .That()
            .ResideInAssembly(apiAssembly)
            .Should()
            .NotDependOnAny(Types()
                .That()
                .HaveName(x => x.Contains("GPL") || x.Contains("AGPL"))
            );

        // Execute the rule
        var violations = rule.Evaluate(Architecture).ToList();
        
        // Assert no violations
        Assert.Empty(violations);
    }

    /// <summary>
    /// Validates that only approved open source licenses are used.
    /// Approved licenses: MIT, Apache 2.0, BSD, ISC
    /// </summary>
    [Fact]
    public void OnlyApprovedLicensesUsed()
    {
        // This is a demonstration test. In a real scenario, you would:
        // 1. Parse the project.assets.json file generated by dotnet restore
        // 2. Query NuGet API for license information
        // 3. Validate against a whitelist

        // For now, we verify that the API doesn't have obviously named GPL packages
        var apiAssembly = Architecture.GetAssembliesByName("TestArchUnit.API").FirstOrDefault();
        
        Assert.NotNull(apiAssembly);
        
        // In production, integrate with NuGet license detection:
        // var licenseValidator = new NuGetLicenseValidator();
        // var violations = licenseValidator.ValidateAssembly(apiAssembly);
        // Assert.Empty(violations);
    }

    /// <summary>
    /// Validates proper dependency injection patterns.
    /// Controllers should depend on interfaces, not concrete implementations.
    /// </summary>
    [Fact]
    public void ControllersShallDependOnInterfaces()
    {
        var rule = Classes()
            .That()
            .HaveNameEndingWith("Controller")
            .And()
            .ResideInNamespace("TestArchUnit.API.Controllers")
            .Should()
            .OnlyDependOnClassesThat()
            .Implement(typeof(object));

        var violations = rule.Evaluate(Architecture).ToList();
        
        // Allow some violations for framework dependencies
        Assert.True(violations.Count < 5, 
            $"Too many controller dependency violations: {violations.Count}");
    }

    /// <summary>
    /// Validates that API controllers are properly decorated.
    /// All controllers should have the ApiController attribute.
    /// </summary>
    [Fact]
    public void AllControllersHaveApiControllerAttribute()
    {
        var rule = Classes()
            .That()
            .HaveNameEndingWith("Controller")
            .And()
            .ResideInNamespace("TestArchUnit.API.Controllers")
            .Should()
            .HaveAnyAttributes();

        var violations = rule.Evaluate(Architecture).ToList();
        
        Assert.Empty(violations);
    }
}

/// <summary>
/// Tests for validating proper naming conventions across the solution.
/// </summary>
public class NamingConventionTests
{
    private static readonly Architecture Architecture =
        new ArchLoader().LoadAssemblies(typeof(NamingConventionTests).Assembly).Build();

    /// <summary>
    /// Validates that all public classes have meaningful names (no generic names).
    /// </summary>
    [Fact]
    public void PublicClassesHaveMeaningfulNames()
    {
        var illegalNames = new[] { "Class1", "Class2", "Test", "Helper", "Utils" };

        var rule = Classes()
            .That()
            .ArePublic()
            .And()
            .ResideInNamespace("TestArchUnit.API")
            .Should()
            .NotHaveNameMatching("^(Class|Test|Helper|Utils)[0-9]*$");

        var violations = rule.Evaluate(Architecture).ToList();
        
        Assert.Empty(violations);
    }
}

/// <summary>
/// Tests for validating proper architecture separation.
/// </summary>
public class ArchitectureLayeringTests
{
    private static readonly Architecture Architecture =
        new ArchLoader().LoadAssemblies(typeof(ArchitectureLayeringTests).Assembly).Build();

    /// <summary>
    /// Validates that controllers are isolated in their namespace.
    /// </summary>
    [Fact]
    public void ControllersAreInControllerNamespace()
    {
        var rule = Classes()
            .That()
            .HaveNameEndingWith("Controller")
            .Should()
            .ResideInNamespace("TestArchUnit.API.Controllers");

        var violations = rule.Evaluate(Architecture).ToList();
        
        Assert.Empty(violations);
    }
}
