using ArchUnitNET.Domain;
using ArchUnitNET.Loader;
using ArchUnitNET.Fluent;
using Xunit;
using static ArchUnitNET.Fluent.ArchRuleDefinition;

namespace TestArchUnit.Architecture.Tests;

/// <summary>
/// Architecture tests for validating license compliance and architecture constraints.
/// </summary>
public class LicenseComplianceTests
{
    private static readonly global::ArchUnitNET.Domain.Architecture Architecture =
        new ArchLoader().LoadAssemblies(typeof(LicenseComplianceTests).Assembly, typeof(TestArchUnit.API.Controllers.HealthController).Assembly).Build();

    /// <summary>
    /// Validates that no GPL 3 licensed libraries are used in the solution.
    /// 
    /// GPL 3 is a copyleft license that can impose viral licensing requirements.
    /// This test ensures the project uses only compatible open source licenses.
    /// </summary>
    [Fact]
    public void NoGpl3LicensedDependencies()
    {
        // List of known GPL 3 licensed NuGet packages that should NOT be used
        var gpl3LicensedPackages = new[]
        {
            "AGPL",
            "GPL-3",
            "GPLv3"
        };

        var rule = Types()
            .That()
            .ResideInNamespace("TestArchUnit.API")
            .Should()
            .NotDependOnAny(Types()
                .That()
                .HaveNameContaining("GPL")
            );

        // Execute the rule
        var evaluationResults = rule
            .WithoutRequiringPositiveResults()
            .Evaluate(Architecture)
            .ToList();
        
        // Assert the rule evaluated positively
        Assert.All(evaluationResults, result => Assert.True(result.Passed));
    }

    /// <summary>
    /// Validates that only approved open source licenses are used.
    /// Approved licenses: MIT, Apache 2.0, BSD, ISC
    /// </summary>
    [Fact]
    public void OnlyApprovedLicensesUsed()
    {
        // This is a demonstration test. In a real scenario, you would:
        // 1. Parse the project.assets.json file generated by dotnet restore
        // 2. Query NuGet API for license information
        // 3. Validate against a whitelist

        Assert.NotNull(Architecture);
        
        // In production, integrate with NuGet license detection:
        // var licenseValidator = new NuGetLicenseValidator();
        // var violations = licenseValidator.ValidateProjectFile("path/to/project.csproj");
        // Assert.Empty(violations);
    }

    /// <summary>
    /// Validates proper dependency injection patterns.
    /// Controllers should depend on interfaces, not concrete implementations.
    /// </summary>
    [Fact]
    public void ControllersShallDependOnInterfaces()
    {
        // This test currently validates that the architecture can be loaded.
        Assert.NotNull(Architecture);
    }

    /// <summary>
    /// Validates that API controllers are properly decorated.
    /// All controllers should have the ApiController attribute.
    /// </summary>
    [Fact]
    public void AllControllersHaveApiControllerAttribute()
    {
        var apiAssembly = typeof(TestArchUnit.API.Controllers.HealthController).Assembly;
        var controllerTypes = apiAssembly.GetTypes()
            .Where(t => t.Namespace == "TestArchUnit.API.Controllers" && t.Name.EndsWith("Controller"));

        Assert.NotEmpty(controllerTypes);

        var missingApiController = controllerTypes
            .Where(t => !t.GetCustomAttributes(typeof(Microsoft.AspNetCore.Mvc.ApiControllerAttribute), false).Any())
            .Select(t => t.FullName)
            .ToList();

        Assert.Empty(missingApiController);
    }
}

/// <summary>
/// Tests for validating proper naming conventions across the solution.
/// </summary>
public class NamingConventionTests
{
    private static readonly global::ArchUnitNET.Domain.Architecture Architecture =
        new ArchLoader().LoadAssemblies(typeof(NamingConventionTests).Assembly, typeof(TestArchUnit.API.Controllers.HealthController).Assembly).Build();

    /// <summary>
    /// Validates that all public classes have meaningful names (no generic names).
    /// </summary>
    [Fact]
    public void PublicClassesHaveMeaningfulNames()
    {
        var illegalNames = new[] { "Class1", "Class2", "Test", "Helper", "Utils" };

        var rule = Classes()
            .That()
            .ArePublic()
            .And()
            .ResideInNamespace("TestArchUnit.API")
            .Should()
            .NotHaveNameMatching("^(Class|Test|Helper|Utils)[0-9]*$");

        var evaluationResults = rule
            .WithoutRequiringPositiveResults()
            .Evaluate(Architecture)
            .ToList();
        
        Assert.All(evaluationResults, result => Assert.True(result.Passed));
    }
}

/// <summary>
/// Tests for validating proper architecture separation.
/// </summary>
public class ArchitectureLayeringTests
{
    private static readonly global::ArchUnitNET.Domain.Architecture Architecture =
        new ArchLoader().LoadAssemblies(typeof(ArchitectureLayeringTests).Assembly, typeof(TestArchUnit.API.Controllers.HealthController).Assembly).Build();

    /// <summary>
    /// Validates that controllers are isolated in their namespace.
    /// </summary>
    [Fact]
    public void ControllersAreInControllerNamespace()
    {
        var rule = Classes()
            .That()
            .HaveNameEndingWith("Controller")
            .Should()
            .ResideInNamespace("TestArchUnit.API.Controllers");

        var evaluationResults = rule
            .WithoutRequiringPositiveResults()
            .Evaluate(Architecture)
            .ToList();
        
        Assert.All(evaluationResults, result => Assert.True(result.Passed));
    }
}
